# docker-compose.yml
services:
  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cloverdash-frontend
    ports:
      - "8080:80"
    # IMPORTANT: Now depends on 'ai-service' instead of 'backend'
    depends_on:
      - ai-service
    networks:
      - clover-net

  # Unified FastAPI Backend + AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: cloverdash-ai
    restart: unless-stopped
    ports:
      - "8000:8000" # Expose port 8000 for the FastAPI service
    # IMPORTANT: Add environment variables for InfluxDB connection
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN} # Reads from your .env file
      - INFLUX_ORG=clover-health
      - INFLUX_BUCKET=ecg-data
    depends_on:
      - influxdb
    networks:
      - clover-net

  # InfluxDB Service
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_ecg
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=sutdwth2025
      - DOCKER_INFLUXDB_INIT_ORG=clover-health
      - DOCKER_INFLUXDB_INIT_BUCKET=ecg-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - clover-net

volumes:
  influxdb_data:

networks:
  clover-net:
    driver: bridge
